/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Business.Car;
import Business.CarDirectory;
import java.awt.CardLayout;
import static javafx.scene.input.KeyCode.Y;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Akshay
 */
public class SearchesJPanel extends javax.swing.JPanel {

   private JPanel userProcessContainerJPanel; 
   private CarDirectory carDirectory;

    SearchesJPanel(JPanel userProcessContainerJPanel, CarDirectory carDirectory) {
       
        initComponents();
        this.userProcessContainerJPanel = userProcessContainerJPanel;
        this.carDirectory = carDirectory;
        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFirstAvailableCar = new javax.swing.JButton();
        btnCountAvailable = new javax.swing.JButton();
        btnCarByBrandName = new javax.swing.JButton();
        btnCarByYear = new javax.swing.JButton();
        btnCarBySeat = new javax.swing.JButton();
        btnCarBySerial = new javax.swing.JButton();
        btnCarByModel = new javax.swing.JButton();
        btnManufacturers = new javax.swing.JButton();
        btnCarAvailable = new javax.swing.JButton();
        btnExpiration = new javax.swing.JButton();
        btnFleetUpdate = new javax.swing.JButton();
        txtBrandName = new javax.swing.JTextField();
        txtManufacturingYear = new javax.swing.JTextField();
        txtMinimum = new javax.swing.JTextField();
        txtMaximum = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtFirstAvailableCar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnMultipleSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setForeground(new java.awt.Color(204, 255, 204));
        setMaximumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Searches");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnFirstAvailableCar.setText("First Available Car");
        btnFirstAvailableCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstAvailableCarActionPerformed(evt);
            }
        });

        btnCountAvailable.setText("Count of available and Unavailable Cars");
        btnCountAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountAvailableActionPerformed(evt);
            }
        });

        btnCarByBrandName.setText("List of Cars by Brand Name");
        btnCarByBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarByBrandNameActionPerformed(evt);
            }
        });

        btnCarByYear.setText("Cars by Year of Manufactuirng");
        btnCarByYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarByYearActionPerformed(evt);
            }
        });

        btnCarBySeat.setText("List of Cars by Seat Capacity");
        btnCarBySeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarBySeatActionPerformed(evt);
            }
        });

        btnCarBySerial.setText("Car having Serial Number");
        btnCarBySerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarBySerialActionPerformed(evt);
            }
        });

        btnCarByModel.setText("List of Cars by Model Number");
        btnCarByModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarByModelActionPerformed(evt);
            }
        });

        btnManufacturers.setText("List Car Manufacturers");
        btnManufacturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufacturersActionPerformed(evt);
            }
        });

        btnCarAvailable.setText("Cars Available in the City");
        btnCarAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarAvailableActionPerformed(evt);
            }
        });

        btnExpiration.setText("List of Cars having Certification Expired");
        btnExpiration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpirationActionPerformed(evt);
            }
        });

        btnFleetUpdate.setText("Fleet Last Update Date");
        btnFleetUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFleetUpdateActionPerformed(evt);
            }
        });

        txtBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Min");

        jLabel3.setText("Max");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnMultipleSearch.setText("Multiple Search Button");
        btnMultipleSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultipleSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCarByBrandName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCarByYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(btnCarBySeat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCarBySerial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCarByModel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCarAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFirstAvailableCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFleetUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMinimum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMaximum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtManufacturingYear, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBrandName)
                                    .addComponent(txtSerialNumber))
                                .addGap(278, 278, 278))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFirstAvailableCar)
                                    .addComponent(txtModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(txtCity))
                                .addGap(0, 278, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManufacturers, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCountAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMultipleSearch)
                        .addGap(63, 63, 63)
                        .addComponent(btnSearch)
                        .addGap(106, 106, 106))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirstAvailableCar)
                    .addComponent(txtFirstAvailableCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarByBrandName)
                    .addComponent(txtBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCarByYear)
                            .addComponent(txtManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCarBySeat)
                            .addComponent(txtMinimum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaximum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(btnCarBySerial))
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarByModel)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarAvailable)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnFleetUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnManufacturers)
                .addGap(18, 18, 18)
                .addComponent(btnExpiration)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnCountAvailable)
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearch)
                            .addComponent(btnMultipleSearch))
                        .addGap(33, 33, 33))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExpirationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpirationActionPerformed
        // TODO add your handling code here:
        int abc=10;
        UpdateJPanel expiredCarsPanel = new UpdateJPanel(userProcessContainerJPanel,carDirectory, abc);
        userProcessContainerJPanel.add("UpdateJPanel", expiredCarsPanel);
            CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
            layout.next(userProcessContainerJPanel);            
    }//GEN-LAST:event_btnExpirationActionPerformed

    private void btnFirstAvailableCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstAvailableCarActionPerformed
        // TODO add your handling code here:
        Car result = carDirectory.firstAvailableCar(txtFirstAvailableCar.getText());
        if(result == null){
            JOptionPane.showMessageDialog(null, "No cars available at the given location.");
        }

        else{
                
                UpdateJPanel panel = new UpdateJPanel(userProcessContainerJPanel, result);
                userProcessContainerJPanel.add("UpdateJPanel", panel);
                CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
                layout.next(userProcessContainerJPanel); 
                
        }
        
        
        
        
        
    }//GEN-LAST:event_btnFirstAvailableCarActionPerformed

    private void btnCarByBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarByBrandNameActionPerformed
        // TODO add your handling code here:
        String x = txtBrandName.getText();
            UpdateJPanel carBrandPanel = new UpdateJPanel(userProcessContainerJPanel, x, carDirectory);
            userProcessContainerJPanel.add("UpdateJPanel",carBrandPanel);
            CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
            layout.next(userProcessContainerJPanel);
        
        
        
    }//GEN-LAST:event_btnCarByBrandNameActionPerformed

    private void btnCarByYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarByYearActionPerformed
        // TODO add your handling code here:
        String year = txtManufacturingYear.getText();
        String abc = "abc";
        UpdateJPanel carsYearPanel = new UpdateJPanel(userProcessContainerJPanel,year,carDirectory, abc );
        userProcessContainerJPanel.add("UpdateJPanel",carsYearPanel);
            CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
            layout.next(userProcessContainerJPanel);                                            
        
        
        
        
    }//GEN-LAST:event_btnCarByYearActionPerformed

    private void btnCarBySeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarBySeatActionPerformed
        // TODO add your handling code here:
        int min = Integer.parseInt(txtMinimum.getText());
        int max = Integer.parseInt(txtMaximum.getText());
        
        Car result = carDirectory.MinMaxSeats(min, max);
        if(result == null){
            JOptionPane.showMessageDialog(null, "No such match found for the Seat Capacity specified!");
        }

        else{
            
            
                UpdateJPanel viewpanel = new UpdateJPanel(userProcessContainerJPanel, carDirectory, min, max);
                userProcessContainerJPanel.add("UpdateJPanel",viewpanel);
                CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
                layout.next(userProcessContainerJPanel);
        }
        
        
        
    }//GEN-LAST:event_btnCarBySeatActionPerformed

    private void btnCarBySerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarBySerialActionPerformed
        // TODO add your handling code here:
        Car result = carDirectory.searchCarBySerialNumber(txtSerialNumber.getText());
        if(result == null){
            JOptionPane.showMessageDialog(null, "No such match found!");
        }

        else{
                String s = "abc";
                UpdateJPanel viewpanel = new UpdateJPanel(userProcessContainerJPanel,s, result);
                userProcessContainerJPanel.add("UpdateJPanel",viewpanel);
                CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
                layout.next(userProcessContainerJPanel);
        }
        
        
        
        
        
    }//GEN-LAST:event_btnCarBySerialActionPerformed

    private void btnCarByModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarByModelActionPerformed
        // TODO add your handling code here:
        Car result = carDirectory.searchCarByModelNumber(txtModelNumber.getText());
        if(result==null){
            JOptionPane.showMessageDialog(null,"No such match found!");
        }
        
        else{
        UpdateJPanel carsModelPanel = new UpdateJPanel(userProcessContainerJPanel,carDirectory,txtModelNumber.getText());
        userProcessContainerJPanel.add("UpdateJPanel",carsModelPanel);
            CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
            layout.next(userProcessContainerJPanel);
        }
        
        
        
    }//GEN-LAST:event_btnCarByModelActionPerformed

    private void btnManufacturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufacturersActionPerformed
        // TODO add your handling code here:
         ViewJPanel panel = new ViewJPanel(userProcessContainerJPanel,carDirectory);
        userProcessContainerJPanel.add("ViewJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
            layout.next(userProcessContainerJPanel);             
    }//GEN-LAST:event_btnManufacturersActionPerformed

    private void btnCarAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarAvailableActionPerformed
        // TODO add your handling code here:
        
        Car result = carDirectory.searchCarByCity(txtCity.getText());
        if(result==null){
            JOptionPane.showMessageDialog(null,"No such match found!");
        }
        
        else{
        String abc = "abc";
         UpdateJPanel carsCityPanel = new UpdateJPanel(userProcessContainerJPanel,txtCity.getText(),abc, carDirectory);
        userProcessContainerJPanel.add("UpdateJPanel",carsCityPanel);
            CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
            layout.next(userProcessContainerJPanel);
        }
        
        
        
        
    }//GEN-LAST:event_btnCarAvailableActionPerformed

    private void btnFleetUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFleetUpdateActionPerformed
        // TODO add your handling code here:
        
        UpdateJPanel panel = new UpdateJPanel(userProcessContainerJPanel,carDirectory);
        userProcessContainerJPanel.add("UpdateJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
            layout.next(userProcessContainerJPanel);
        
        
        
    }//GEN-LAST:event_btnFleetUpdateActionPerformed

    private void btnCountAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountAvailableActionPerformed
        // TODO add your handling code here:
        UpdateJPanel panel = new UpdateJPanel(userProcessContainerJPanel,carDirectory);
        userProcessContainerJPanel.add("UpdateJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
            layout.next(userProcessContainerJPanel);
        
        
        
    }//GEN-LAST:event_btnCountAvailableActionPerformed

    private void txtBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandNameActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        
        String brand = txtBrandName.getText();
        String year = txtManufacturingYear.getText();
        String min = txtMinimum.getText();
        String max = txtMaximum.getText();
        String model = txtModelNumber.getText();
        String city = txtCity.getText(); 
        
        
        if(brand.isEmpty() && year.isEmpty() && model.isEmpty() && city.isEmpty() )
        {
        JOptionPane.showMessageDialog(null,"Kindly provide some Search Criteria!");
        }
        else{
            UpdateJPanel panel = new UpdateJPanel(userProcessContainerJPanel,carDirectory,brand,year,min,max,model,city);
            userProcessContainerJPanel.add("UpdateJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
            layout.next(userProcessContainerJPanel);
        }
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnMultipleSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultipleSearchActionPerformed
        // TODO add your handling code here:
        
        MultipleSearchJPanel panel = new MultipleSearchJPanel(userProcessContainerJPanel,carDirectory);
        userProcessContainerJPanel.add("MultipleSearchJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
            layout.next(userProcessContainerJPanel);
        
        
    }//GEN-LAST:event_btnMultipleSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarAvailable;
    private javax.swing.JButton btnCarByBrandName;
    private javax.swing.JButton btnCarByModel;
    private javax.swing.JButton btnCarBySeat;
    private javax.swing.JButton btnCarBySerial;
    private javax.swing.JButton btnCarByYear;
    private javax.swing.JButton btnCountAvailable;
    private javax.swing.JButton btnExpiration;
    private javax.swing.JButton btnFirstAvailableCar;
    private javax.swing.JButton btnFleetUpdate;
    private javax.swing.JButton btnManufacturers;
    private javax.swing.JButton btnMultipleSearch;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtFirstAvailableCar;
    private javax.swing.JTextField txtManufacturingYear;
    private javax.swing.JTextField txtMaximum;
    private javax.swing.JTextField txtMinimum;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables

}
